name: Compilation Test

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install gnuplot
      run: sudo apt install gnuplot-nox
    
    - name: Install sciplot
      run: git clone https://github.com/sciplot/sciplot --recursive &&
           cd sciplot &&
           mkdir build && cd build &&
           cmake .. &&
           sudo cmake --build . --target install

    - name: Compilation Test
      run: ./test.sh
